// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotZtAAnokcJdseLvGdf7_cMVVgbS-JIw',
    appId: '1:646940855383:web:bce605c4e601491fcf6712',
    messagingSenderId: '646940855383',
    projectId: 'daylimoney-5d1e4',
    authDomain: 'daylimoney-5d1e4.firebaseapp.com',
    storageBucket: 'daylimoney-5d1e4.firebasestorage.app',
    measurementId: 'G-J7GVCWGF8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUSDfd2hsi3Ck2aIlOxV1EhQeijiRaga4',
    appId: '1:646940855383:android:959dae42acf31d05cf6712',
    messagingSenderId: '646940855383',
    projectId: 'daylimoney-5d1e4',
    storageBucket: 'daylimoney-5d1e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvTWNUui4bndn2fGNzIRdEoBzzZSW_vg',
    appId: '1:646940855383:ios:7123177e10e0c93ecf6712',
    messagingSenderId: '646940855383',
    projectId: 'daylimoney-5d1e4',
    storageBucket: 'daylimoney-5d1e4.firebasestorage.app',
    iosBundleId: 'com.example.dailyMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvTWNUui4bndn2fGNzIRdEoBzzZSW_vg',
    appId: '1:646940855383:ios:7123177e10e0c93ecf6712',
    messagingSenderId: '646940855383',
    projectId: 'daylimoney-5d1e4',
    storageBucket: 'daylimoney-5d1e4.firebasestorage.app',
    iosBundleId: 'com.example.dailyMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotZtAAnokcJdseLvGdf7_cMVVgbS-JIw',
    appId: '1:646940855383:web:ae1302a20bed94cfcf6712',
    messagingSenderId: '646940855383',
    projectId: 'daylimoney-5d1e4',
    authDomain: 'daylimoney-5d1e4.firebaseapp.com',
    storageBucket: 'daylimoney-5d1e4.firebasestorage.app',
    measurementId: 'G-D044TKQS4D',
  );
}
